language: ruby

bundler_args: '--without production development -j8'

before_install:
  - sudo apt-get install libxml2-dev libxslt1-dev libcurl3 libcurl3-gnutls libcurl4-openssl-dev
  - sudo apt-get install libmysqlclient-dev
  - gem update --system
  - gem --version
  - mysql -e "create database IF NOT EXISTS \`test\`;" -uroot 

before_script:
  - mysql -e "create database \`cube-test\`;"

rvm:
  - 2.0.0
