require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FiltersController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Filter. As you add validations to Filter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FiltersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  # devise sign in and sign out
  before :each do
    @request.env['devise.mapping'] = Devise.mappings[:admin]
    @admin = create :admin
    sign_in @admin
  end

  after :each do
    sign_out @admin
  end

  describe "GET index" do
    it "assigns all filters as @filters" do
      filter = Filter.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:filters)).to eq([filter])
    end
  end

  describe "GET show" do
    it "assigns the requested filter as @filter" do
      filter = Filter.create! valid_attributes
      get :show, {:id => filter.to_param}, valid_session
      expect(assigns(:filter)).to eq(filter)
    end
  end

  describe "GET new" do
    it "assigns a new filter as @filter" do
      get :new, {}, valid_session
      expect(assigns(:filter)).to be_a_new(Filter)
    end
  end

  describe "GET edit" do
    it "assigns the requested filter as @filter" do
      filter = Filter.create! valid_attributes
      get :edit, {:id => filter.to_param}, valid_session
      expect(assigns(:filter)).to eq(filter)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Filter" do
        expect {
          post :create, {:filter => valid_attributes}, valid_session
        }.to change(Filter, :count).by(1)
      end

      it "assigns a newly created filter as @filter" do
        post :create, {:filter => valid_attributes}, valid_session
        expect(assigns(:filter)).to be_a(Filter)
        expect(assigns(:filter)).to be_persisted
      end

      it "redirects to the created filter" do
        post :create, {:filter => valid_attributes}, valid_session
        expect(response).to redirect_to(Filter.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved filter as @filter" do
        post :create, {:filter => invalid_attributes}, valid_session
        expect(assigns(:filter)).to be_a_new(Filter)
      end

      it "re-renders the 'new' template" do
        post :create, {:filter => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested filter" do
        filter = Filter.create! valid_attributes
        put :update, {:id => filter.to_param, :filter => new_attributes}, valid_session
        filter.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested filter as @filter" do
        filter = Filter.create! valid_attributes
        put :update, {:id => filter.to_param, :filter => valid_attributes}, valid_session
        expect(assigns(:filter)).to eq(filter)
      end

      it "redirects to the filter" do
        filter = Filter.create! valid_attributes
        put :update, {:id => filter.to_param, :filter => valid_attributes}, valid_session
        expect(response).to redirect_to(filter)
      end
    end

    describe "with invalid params" do
      it "assigns the filter as @filter" do
        filter = Filter.create! valid_attributes
        put :update, {:id => filter.to_param, :filter => invalid_attributes}, valid_session
        expect(assigns(:filter)).to eq(filter)
      end

      it "re-renders the 'edit' template" do
        filter = Filter.create! valid_attributes
        put :update, {:id => filter.to_param, :filter => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested filter" do
      filter = Filter.create! valid_attributes
      expect {
        delete :destroy, {:id => filter.to_param}, valid_session
      }.to change(Filter, :count).by(-1)
    end

    it "redirects to the filters list" do
      filter = Filter.create! valid_attributes
      delete :destroy, {:id => filter.to_param}, valid_session
      expect(response).to redirect_to(filters_url)
    end
  end

end
